services:
    EonX\EasyCore\Bridge\Symfony\ApiPlatform\Routing\IriConverter:
        decorates: api_platform.iri_converter
        arguments: ['@EonX\EasyCore\Bridge\Symfony\ApiPlatform\Routing\IriConverter.inner']
