services:
    EonX\EasyCore\Bridge\Symfony\ApiPlatform\Pagination\CustomPaginationListener:
        tags:
            - { name: kernel.event_listener, event: kernel.view, priority: 17 }

    EonX\EasyCore\Bridge\Symfony\ApiPlatform\Pagination\SerializerContextBuilder:
        autoconfigure: false
        decorates: 'api_platform.serializer.context_builder'
        arguments:
            - '@EonX\EasyCore\Bridge\Symfony\ApiPlatform\Pagination\SerializerContextBuilder.inner'
