services:
    api_platform.data_persister:
        class: EonX\EasyCore\Bridge\Symfony\ApiPlatform\DataPersister\ChainSimpleDataPersister
        arguments:
            - '@service_container'
            - '@event_dispatcher'
            - null
            - !tagged_iterator api_platform.data_persister

    EonX\EasyCore\Bridge\Symfony\ApiPlatform\Listeners\ResolveRequestAttributesListener:
        autoconfigure: true
        arguments:
            - '@request_stack'
