services:
    EonX\EasyCore\Bridge\Symfony\ApiPlatform\Listeners\AddValidationErrorsOnJobLogListener:
        tags:
            - { name: kernel.event_listener, event: EonX\EasyAsync\Events\JobLogFailedEvent }
