services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EonX\EasyCore\Lock\LockServiceInterface:
        class: EonX\EasyCore\Lock\LockService

    EonX\EasyCore\Bridge\Symfony\Messenger\ProcessWithLockMiddleware: null
